spring:
  application:
    name: chatbot

server:
  port: ${PORT:8080}

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}
    url: ${DEEPSEEK_API_URL:https://api.deepseek.com/v1/chat/completions}

logging:
  level:
    root: INFO
    com.bo.chatbot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
